M48
; DRILL file {KiCad (6.0.6-0)} date Monday, 04 July 2022 at 11:11:14
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-04T11:11:14+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X2.6378Y-2.7165
X3.3858Y-4.1339
X3.5039Y-3.189
X4.7244Y-3.0315
T0
M30
