M48
; DRILL file {KiCad (6.0.6-0)} date Monday, 04 July 2022 at 11:08:51
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-04T11:08:51+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X3.0709Y-5.3543
X3.7008Y-4.3701
X4.7244Y-4.685
X4.7638Y-5.3543
T0
M30
