M48
; DRILL file {KiCad (6.0.6-0)} date Monday, 04 July 2022 at 11:09:16
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-04T11:09:16+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.315Y-4.9606
X6.063Y-3.937
X6.4961Y-3.3071
X6.5748Y-4.9606
T0
M30
